# Generated by Django 4.2.1 on 2023-11-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0004_alter_product_p_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_id',
            new_name='purchase_invoice_number',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase_item_id',
        ),
    ]
