# Generated by Django 4.2.1 on 2023-11-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0006_purchaseitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
