# Generated by Django 4.2.1 on 2023-11-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0007_alter_purchaseitem_quantity_alter_purchaseitem_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='bill',
            field=models.FileField(null=True, upload_to='Purchase Bills'),
        ),
    ]
