# Generated by Django 4.2.1 on 2023-11-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0009_alter_purchase_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_id',
            new_name='invoice_number',
        ),
    ]
