# Generated by Django 4.2.1 on 2023-11-05 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0010_rename_sale_id_sale_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='sale_item_id',
        ),
    ]
