# Generated by Django 4.2.1 on 2023-11-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0011_remove_saleitem_sale_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
