# Generated by Django 4.2.1 on 2023-11-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Developer', '0012_saleitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
